services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: tododb
      DB_PORT: 5432
